### ISSUE TITLE
doesn't catch arithmetic operations

### ISSUE THREAD

**Issue by electrovir** [electrovir/stylelint-plugin-color#3]
```less
div {
    color: @my-color - #432;
}
```
should fail when options are
```json
{
    "mode": "block",
    "types": ["hex"]
}
```

but it does not
